/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef EXAMPLE_PACKAGE_BAKE_CONFIG_H
#define EXAMPLE_PACKAGE_BAKE_CONFIG_H

/* Generated includes are specific to the bake environment. If a project is not
 * built with bake, it will have to provide alternative methods for including
 * its dependencies. */
/* Headers of public dependencies */
/* No dependencies */

/* Headers of private dependencies */
#ifdef EXAMPLE_PACKAGE_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#ifndef EXAMPLE_PACKAGE_STATIC
  #if EXAMPLE_PACKAGE_IMPL && (defined(_MSC_VER) || defined(__MINGW32__))
    #define EXAMPLE_PACKAGE_EXPORT __declspec(dllexport)
  #elif EXAMPLE_PACKAGE_IMPL
    #define EXAMPLE_PACKAGE_EXPORT __attribute__((__visibility__("default")))
  #elif defined _MSC_VER
    #define EXAMPLE_PACKAGE_EXPORT __declspec(dllimport)
  #else
    #define EXAMPLE_PACKAGE_EXPORT
  #endif
#else
  #define EXAMPLE_PACKAGE_EXPORT
#endif

#endif

